-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 20:07:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
# para drop
#SET FOREIGN_KEY_CHECKS=0; DROP TABLE Post; SET FOREIGN_KEY_CHECKS=1;
#SET FOREIGN_KEY_CHECKS=0; DROP TABLE Usuarios; SET FOREIGN_KEY_CHECKS=1;
#SET FOREIGN_KEY_CHECKS=0; DROP TABLE Passaros; SET FOREIGN_KEY_CHECKS=1;
#drop table if exists Usuarios_Passaros;
#drop table if exists Tag;
#drop table if exists Mencionar;
#drop table if exists Visualizado;
#drop database if exists mydb;

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Passaros`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Passaros` (
  `idPassaros` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Especie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPassaros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `idPost` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `Texto` VARCHAR(300) NULL,
  `URL` VARCHAR(45) NULL,
  `Atividade` TINYINT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk_Post_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios_Passaros`
-- -----------------------------------------------------
drop table if exists Usuarios_Passaros;
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios_Passaros` (
  `Usuarios_idUsuarios` INT NOT NULL,
  `Passaros_idPassaros` INT NOT NULL,
  INDEX `fk_Usuarios_Passaros_Usuarios_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  INDEX `fk_Usuarios_Passaros_Passaros1_idx` (`Passaros_idPassaros` ASC) VISIBLE,
  PRIMARY KEY (`Usuarios_idUsuarios`, `Passaros_idPassaros`),
  CONSTRAINT `fk_Usuarios_Passaros_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Passaros_Passaros1`
    FOREIGN KEY (`Passaros_idPassaros`)
    REFERENCES `mydb`.`Passaros` (`idPassaros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visualizado`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Visualizado` (
  `Post_idPost` INT NOT NULL,
  `Usuarios_idUsuarios` INT NOT NULL,
  `IP` VARCHAR(45) NOT NULL,
  `Browser` VARCHAR(45) NOT NULL,
  `Aparelho` VARCHAR(45) NOT NULL,
  `Data` DATETIME NOT NULL,
  PRIMARY KEY (`Post_idPost`, `Usuarios_idUsuarios`),
  INDEX `fk_View_Usuarios1_idx` (`Usuarios_idUsuarios` ASC) VISIBLE,
  CONSTRAINT `fk_View_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_View_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tag`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Tag` (
  `Passaros_idPassaros` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  `Ativar` TINYINT NULL,
  PRIMARY KEY (`Passaros_idPassaros`, `Post_idPost`),
  INDEX `fk_Tag_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Tag_Passaros1`
    FOREIGN KEY (`Passaros_idPassaros`)
    REFERENCES `mydb`.`Passaros` (`idPassaros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mencionar`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `mydb`.`Mencionar` (
  `Usuarios_idUsuarios` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  `Ativar` TINYINT NULL,
  PRIMARY KEY (`Usuarios_idUsuarios`, `Post_idPost`),
  INDEX `fk_Mencionar_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Mencionar_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `mydb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mencionar_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TRIGGER IF EXISTS ativar;
DELIMITER // 
CREATE TRIGGER ativar
BEFORE UPDATE ON Post
FOR EACH ROW
BEGIN
    UPDATE Tag, Post
        SET Tag.Ativar = Post.Atividade where Tag.Post_idPost = Post.idPost;

	UPDATE Mencionar, Post
        SET Mencionar.Ativar = Post.Atividade where Mencionar.Post_idPost = Post.idPost;
END//
DELIMITER ;